--baza implementirana na S18108
CREATE TABLE OSOBA
(
IDOsobe NUMBER PRIMARY KEY, 
Ime VARCHAR2(20) NOT NULL,
Prezime VARCHAR2(30) NOT NULL,
MaticniBroj VARCHAR2(13) UNIQUE CONSTRAINT MaticniBroj_CK CHECK (LENGTH(MaticniBroj) = 13)
);
CREATE TABLE STOMATOLOSKA_STOLICA
(
IDStolice NUMBER PRIMARY KEY,
Proizvodjac VARCHAR2(50),
DatumProizvodnje DATE,
IDTehnOdrz NUMBER REFERENCES OSOBA(IDOsobe) ON DELETE SET NULL
);

CREATE TABLE ODELJENJE
(
ID NUMBER PRIMARY KEY,
Sifra NUMBER UNIQUE,  
Tip VARCHAR2(50) NOT NULL,
DatumIzgradnje DATE,
IDSpecijaliste NUMBER REFERENCES OSOBA(IDOsobe) ON DELETE SET NULL
);

CREATE TABLE MEDICINSKO_OSOBLJE
(
IDOsobe NUMBER PRIMARY KEY REFERENCES OSOBA(IDOsobe),
GodineRadnogStaza NUMBER(2) NOT NULL,
TipMedOsoblja VARCHAR2(50) CONSTRAINT TipMedOsoblja_CK CHECK (TipMedOsoblja IN ('Stomatolog', 'Opsta praksa','Specijalista')) NOT NULL,
BrojOrdinacije NUMBER(4),
Specijalnost VARCHAR2(40), 
Smena NUMBER(1) CONSTRAINT Smena_CK CHECK (Smena=1 OR Smena=2),
IDStolice NUMBER REFERENCES STOMATOLOSKA_STOLICA(IDStolice) ON DELETE SET NULL,
CHECK ((TipMedOsoblja='Opsta praksa' AND BrojOrdinacije IS NOT NULL)
OR (TipMedOsoblja='Specijalista' AND Specijalnost IS NOT NULL)
OR (TipMedOsoblja='Stomatolog'AND Smena IS NOT NULL AND IDStolice IS NOT NULL)) 
);

CREATE TABLE NEMEDICINSKO_OSOBLJE
(
IDOsobe NUMBER PRIMARY KEY REFERENCES OSOBA(IDOsobe),
TipNemedOsoblja VARCHAR2(50) CONSTRAINT TipNemedOsoblja_CK CHECK (TipNemedOsoblja IN ('Higijenicar', 'Tehnicko odrzavanje')) NOT NULL,
Struka VARCHAR2(50),
CHECK ((TipNemedOsoblja='Tehnicko odrzavanje' AND Struka IS NOT NULL)
OR (TipNemedOsoblja='Higijenicar' ))
);

CREATE TABLE PACIJENT
(
IDOsobe NUMBER PRIMARY KEY REFERENCES OSOBA(IDOsobe),
TipPacijenta VARCHAR2(50) CONSTRAINT TipPacijenta_CK CHECK (TipPacijenta IN ('Ambulanta', 'Stacionar')) NOT NULL,
Adresa VARCHAR2(30),
DatumPrijema DATE,
DatumOtpusta DATE,
IDStomatologa NUMBER REFERENCES MEDICINSKO_OSOBLJE(IDOsobe) ON DELETE SET NULL,
VrstaIntervencije VARCHAR2(30),
DatumIntervencije DATE,
IDOdeljenja NUMBER REFERENCES ODELJENJE(ID) ON DELETE CASCADE,
IDLekaraOP NUMBER REFERENCES MEDICINSKO_OSOBLJE(IDOsobe) ON DELETE SET NULL,
CHECK ((TipPacijenta='Ambulanta' AND Adresa IS NOT NULL)
OR (TipPacijenta='Stacionar'AND DatumPrijema IS NOT NULL AND DatumOtpusta IS NOT NULL))
);

CREATE TABLE ODRZAVA_HIGIJENU
(
ID NUMBER PRIMARY KEY,
IDHigijenicara NUMBER REFERENCES OSOBA(IDOsobe) ON DELETE CASCADE, 
IDOdeljenja NUMBER REFERENCES ODELJENJE(ID) ON DELETE CASCADE
);
CREATE UNIQUE INDEX index1 ON ODRZAVA_HIGIJENU(IDHIGIJENICARA,IDODELJENJA);

--SEKVENCE I TRIGERI
CREATE SEQUENCE "OSOBA_IDOSOBE_SEQ" MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 NOCACHE ORDER NOCYCLE;
CREATE SEQUENCE "ODELJENJE_ID_SEQ" MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 NOCACHE ORDER NOCYCLE;
CREATE SEQUENCE "STOMATOLOSKA_STOLICA_ID_SEQ" MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 NOCACHE ORDER NOCYCLE;
CREATE SEQUENCE "ODRZAVA_HIGIJENU_ID_SEQ" MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 NOCACHE ORDER NOCYCLE;


CREATE OR REPLACE TRIGGER "OSOBA_PK"
BEFORE INSERT
ON OSOBA
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
    SELECT OSOBA_IDOSOBE_SEQ.NEXTVAL INTO :NEW.IDOsobe FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER "ODELJENJE_PK"
BEFORE INSERT
ON ODELJENJE
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
    SELECT ODELJENJE_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
 /
 
CREATE OR REPLACE TRIGGER "STOMATOLOSKA_STOLICA_PK"
BEFORE INSERT
ON STOMATOLOSKA_STOLICA
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
    SELECT STOMATOLOSKA_STOLICA_ID_SEQ.NEXTVAL INTO :NEW.IDStolice FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER "ODRZAVA_HIGIJENU_PK"
BEFORE INSERT
ON ODRZAVA_HIGIJENU
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
    SELECT ODRZAVA_HIGIJENU_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
alter trigger "S18108"."ODELJENJE_PK" enable;

alter trigger "S18108"."OSOBA_PK" enable;

alter trigger "S18108"."STOMATOLOSKA_STOLICA_PK" enable;

alter trigger "S18108"."ODRZAVA_HIGIJENU_PK" enable;


